services:
  backend:
    build: .
    ports:
      - "3001:3000"  # Ändere zu 3000:3000 falls du direkt 3000 nutzen willst
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/paletten

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
