services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

  backend:
    build: .
    container_name: paletten-backend
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/deineDB
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mongodb_data:
