services:
  backend:
    build: .
    ports:
      - "3000:3000"   # ❗ Muss auf 3000:3000 gesetzt sein!

    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/paletten

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
