services:
  backend:
    build: .
    ports:
      - "3000:3000"  # Vorher war hier 3001:3000

    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/paletten

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
